# Generated by Django 5.2.8 on 2026-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
